### ISSUE TITLE
Broken due to pull request #1

### ISSUE THREAD

**Issue by cakenggt** [maeltm/node-google-id-token-verifier#2]
Even though this passed all the tests, it does not work in production. This is due to the crypto library trying to decode a PEM key, and instead finding a different type of key. V3 of the oAuth2 doesn't have the PEM keys anymore.

I would suggest rolling back pull request #1, as I don't know enough about the crypto library to know how to verify the new keys in the pull request.

**Comment by maeltm** [comment]
I worked to get PEM format from modulus n and exponent e. I cannot do test in production now. so if possible, can you test code in https://github.com/maeltm/node-google-id-token-verifier/tree/fromDiscoveryDoc

**Comment by maeltm** [comment]
Fixed this issue 30036004407ed4a511c50851b06a210b1ed6d708
